FROM docker.io/debian:stable-slim AS build

WORKDIR /usr/src/sdk

ARG HAXE_VERSION=4.3.7

RUN apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		ca-certificates \
		gpgv \
		wget \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/cache/*

RUN wget https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2024.9.1_all.deb \
	&& (sha256sum deb-multimedia-keyring_2024.9.1_all.deb | grep -q '^8dc6cbb266c701cfe58bd1d2eb9fe2245a1d6341c7110cfbfe3a5a975dcf97ca ') \
	&& dpkg -i deb-multimedia-keyring_2024.9.1_all.deb

COPY build-misc/dmo.sources /etc/apt/sources.list.d/dmo.sources
COPY build-misc/apt-pref /etc/apt/preferences.d/apt-pref

RUN apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		build-essential \
		autoconf \
		automake \
		libtool \
		pkg-config \
		git \
		npm \
		esbuild \
		libdatachannel-dev \
		libopus-dev \
		libc-ares-dev \
		libexpat1-dev \
		libssl-dev \
		zlib1g-dev \
		libmbedtls-dev \
		libsqlite3-dev \
		libpcre2-dev \
		neko \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/cache/*

RUN git clone https://github.com/strophe/libstrophe \
	&& cd libstrophe \
	 && ./bootstrap.sh \
	 && ./configure --enable-cares --prefix=/usr \
	 && make \
	 && make install

ADD https://github.com/HaxeFoundation/haxe/releases/download/${HAXE_VERSION}/haxe-${HAXE_VERSION}-linux64.tar.gz /tmp/haxe.tar.gz

RUN mkdir /opt/haxe \
 && tar xzf /tmp/haxe.tar.gz --strip-components=1 -C /opt/haxe \
 && mv /opt/haxe/haxe /opt/haxe/haxelib /usr/local/bin

# Just need a newer version to actually run make ci with
# For the nodejs sqlite tests, since sqlite was added to nodejs in 22
ADD https://nodejs.org/dist/v22.22.2/node-v22.22.2-linux-x64.tar.xz /tmp/nodejs.tar.xz

RUN mkdir /opt/nodejs \
 && tar xGf /tmp/nodejs.tar.xz --strip-components=1 -C /opt/nodejs \
 && mv /opt/nodejs/bin/node /usr/local/bin/nodejs

# Hack to disable TLS 1.3: OpenSSL 3.5.0 (currently in Debian testing) emits
# signficiantly larger ClientHello packets due to post-quantum key algorithms.
# The large packets get fragmented and this causes handshakes to fail in some
# networks, including on our CI workers. Warrants further investigation.
RUN printf '#!/bin/bash\nexec /usr/local/bin/nodejs --tls-max-v1.2 "$@"' > /usr/local/bin/node \
	&& chmod a+x /usr/local/bin/node

RUN rm /etc/apt/sources.list.d/dmo.sources
RUN npx playwright install --with-deps

COPY Makefile *.hxml /usr/src/sdk/

RUN haxelib setup /opt/haxe
ENV HAXE_STD_PATH=/opt/haxe/std
RUN make hx-build-dep

COPY npm /usr/src/sdk/npm
RUN cd npm && npm install && npm install @playwright/test @sqlite.org/sqlite-wasm
RUN ln -s npm/node_modules node_modules

COPY . /usr/src/sdk/
RUN git fetch --tags

RUN make ci

RUN make -j$(nproc)
RUN cd cpp && make clean
RUN rm -rf npm/node_modules npm/package-lock.json npm/api-extractor.json npm/tsconfig.json

FROM docker.io/debian:stable-slim

WORKDIR /opt/sdk

COPY --from=build /usr/src/sdk/cpp ./cpp
COPY --from=build /usr/src/sdk/libborogove.so ./libborogove.so
COPY --from=build /usr/src/sdk/libborogove.a ./libborogove.a
COPY --from=build /usr/src/sdk/libborogove.batteriesincluded.so ./libborogove.batteriesincluded.so
COPY --from=build /usr/src/sdk/npm ./npm

CMD ["cp", "-R", "/opt/sdk", "/output"]
