/* tslint:disable */// Generated by Haxe TypeScript Declaration Generator :)

export const enum borogove_UiState {
	Pinned = 0,
	Open = 1,
	Closed = 2,
	Invited = 3,
}

export const enum borogove_calls_CallStatus {
	NoCall = 0,
	Incoming = 1,
	Outgoing = 2,
	Connecting = 3,
	Ongoing = 4,
	Failed = 5,
}

export const enum borogove_MessageDirection {
	MessageReceived = 0,
	MessageSent = 1,
}

export const enum borogove_EncryptionStatus {
	DecryptionSuccess = 0,
	DecryptionFailure = 1,
}

export const enum borogove_MessageStatus {
	MessagePending = 0,
	MessageDeliveredToServer = 1,
	MessageDeliveredToDevice = 2,
	MessageFailedToSend = 3,
}

export const enum borogove_MessageType {
	MessageChat = 0,
	MessageCall = 1,
	MessageChannel = 2,
	MessageChannelPrivate = 3,
}

export const enum borogove_UserState {
	Gone = 0,
	Inactive = 1,
	Active = 2,
	Composing = 3,
	Paused = 4,
}

export const enum borogove_ChatMessageEvent {
	DeliveryEvent = 0,
	CorrectionEvent = 1,
	ReactionEvent = 2,
	StatusEvent = 3,
}

export const enum borogove_ReactionUpdateKind {
	EmojiReactions = 0,
	AppendReactions = 1,
	CompleteReactions = 2,
}