/* tslint:disable */ // Generated by Haxe TypeScript Declaration Generator :)
export var borogove_UiState;
(function (borogove_UiState) {
    borogove_UiState[borogove_UiState["Pinned"] = 0] = "Pinned";
    borogove_UiState[borogove_UiState["Open"] = 1] = "Open";
    borogove_UiState[borogove_UiState["Closed"] = 2] = "Closed";
    borogove_UiState[borogove_UiState["Invited"] = 3] = "Invited";
})(borogove_UiState || (borogove_UiState = {}));
export var borogove_calls_CallStatus;
(function (borogove_calls_CallStatus) {
    borogove_calls_CallStatus[borogove_calls_CallStatus["NoCall"] = 0] = "NoCall";
    borogove_calls_CallStatus[borogove_calls_CallStatus["Incoming"] = 1] = "Incoming";
    borogove_calls_CallStatus[borogove_calls_CallStatus["Outgoing"] = 2] = "Outgoing";
    borogove_calls_CallStatus[borogove_calls_CallStatus["Connecting"] = 3] = "Connecting";
    borogove_calls_CallStatus[borogove_calls_CallStatus["Ongoing"] = 4] = "Ongoing";
    borogove_calls_CallStatus[borogove_calls_CallStatus["Failed"] = 5] = "Failed";
})(borogove_calls_CallStatus || (borogove_calls_CallStatus = {}));
export var borogove_MessageDirection;
(function (borogove_MessageDirection) {
    borogove_MessageDirection[borogove_MessageDirection["MessageReceived"] = 0] = "MessageReceived";
    borogove_MessageDirection[borogove_MessageDirection["MessageSent"] = 1] = "MessageSent";
})(borogove_MessageDirection || (borogove_MessageDirection = {}));
export var borogove_EncryptionStatus;
(function (borogove_EncryptionStatus) {
    borogove_EncryptionStatus[borogove_EncryptionStatus["DecryptionSuccess"] = 0] = "DecryptionSuccess";
    borogove_EncryptionStatus[borogove_EncryptionStatus["DecryptionFailure"] = 1] = "DecryptionFailure";
})(borogove_EncryptionStatus || (borogove_EncryptionStatus = {}));
export var borogove_MessageStatus;
(function (borogove_MessageStatus) {
    borogove_MessageStatus[borogove_MessageStatus["MessagePending"] = 0] = "MessagePending";
    borogove_MessageStatus[borogove_MessageStatus["MessageDeliveredToServer"] = 1] = "MessageDeliveredToServer";
    borogove_MessageStatus[borogove_MessageStatus["MessageDeliveredToDevice"] = 2] = "MessageDeliveredToDevice";
    borogove_MessageStatus[borogove_MessageStatus["MessageFailedToSend"] = 3] = "MessageFailedToSend";
})(borogove_MessageStatus || (borogove_MessageStatus = {}));
export var borogove_MessageType;
(function (borogove_MessageType) {
    borogove_MessageType[borogove_MessageType["MessageChat"] = 0] = "MessageChat";
    borogove_MessageType[borogove_MessageType["MessageCall"] = 1] = "MessageCall";
    borogove_MessageType[borogove_MessageType["MessageChannel"] = 2] = "MessageChannel";
    borogove_MessageType[borogove_MessageType["MessageChannelPrivate"] = 3] = "MessageChannelPrivate";
})(borogove_MessageType || (borogove_MessageType = {}));
export var borogove_UserState;
(function (borogove_UserState) {
    borogove_UserState[borogove_UserState["Gone"] = 0] = "Gone";
    borogove_UserState[borogove_UserState["Inactive"] = 1] = "Inactive";
    borogove_UserState[borogove_UserState["Active"] = 2] = "Active";
    borogove_UserState[borogove_UserState["Composing"] = 3] = "Composing";
    borogove_UserState[borogove_UserState["Paused"] = 4] = "Paused";
})(borogove_UserState || (borogove_UserState = {}));
export var borogove_ChatMessageEvent;
(function (borogove_ChatMessageEvent) {
    borogove_ChatMessageEvent[borogove_ChatMessageEvent["DeliveryEvent"] = 0] = "DeliveryEvent";
    borogove_ChatMessageEvent[borogove_ChatMessageEvent["CorrectionEvent"] = 1] = "CorrectionEvent";
    borogove_ChatMessageEvent[borogove_ChatMessageEvent["ReactionEvent"] = 2] = "ReactionEvent";
    borogove_ChatMessageEvent[borogove_ChatMessageEvent["StatusEvent"] = 3] = "StatusEvent";
})(borogove_ChatMessageEvent || (borogove_ChatMessageEvent = {}));
export var borogove_ReactionUpdateKind;
(function (borogove_ReactionUpdateKind) {
    borogove_ReactionUpdateKind[borogove_ReactionUpdateKind["EmojiReactions"] = 0] = "EmojiReactions";
    borogove_ReactionUpdateKind[borogove_ReactionUpdateKind["AppendReactions"] = 1] = "AppendReactions";
    borogove_ReactionUpdateKind[borogove_ReactionUpdateKind["CompleteReactions"] = 2] = "CompleteReactions";
})(borogove_ReactionUpdateKind || (borogove_ReactionUpdateKind = {}));
