declare function _default(dbname: any, media: any, tokenize: any, stemmer: any): Promise<{
    lastId: (account: any, jid: any) => Promise<any>;
    storeChats: (account: any, chats: any) => void;
    getChats: (account: any) => Promise<any[]>;
    getChatsUnreadDetails: (account: any, chatsArray: any) => Promise<any[]>;
    getMessage: (account: any, chatId: any, serverId: any, localId: any) => Promise<import("./borogove.js").borogove_ChatMessage>;
    storeReaction: (account: any, update: any) => Promise<import("./borogove.js").borogove_ChatMessage>;
    storeMessages(account: any, messages: any): Promise<any[]>;
    storeMessage: (account: any, message: any, callback: any) => void;
    updateMessage: (account: any, message: any) => void;
    updateMessageStatus: (account: any, localId: any, status: any, statusText: any) => Promise<import("./borogove.js").borogove_ChatMessage>;
    getMessagesBefore: (account: any, chatId: any, beforeId: any, beforeTime: any) => Promise<import("./borogove.js").borogove_ChatMessage[]>;
    getMessagesAfter: (account: any, chatId: any, afterId: any, afterTime: any) => Promise<import("./borogove.js").borogove_ChatMessage[]>;
    getMessagesAround: (account: any, chatId: any, id: any, timeArg: any) => Promise<import("./borogove.js").borogove_ChatMessage[]>;
    getMessagesFromCursor: (cursor: any, id: any, bound: any) => Promise<import("./borogove.js").borogove_ChatMessage[]>;
    searchMessages: (account: any, chatId: any, q: any, callback: any) => void;
    hasMedia: (hashAlgorithm: any, hash: any) => any;
    removeMedia: (hashAlgorithm: any, hash: any) => void;
    storeMedia: (mime: any, buffer: any) => any;
    storeCaps: (caps: any) => void;
    getCaps: (ver: any) => Promise<borogove_Caps>;
    storeLogin: (login: any, clientId: any, displayName: any, token: any) => void;
    storeOmemoId: (account: any, omemoId: any) => void;
    storeOmemoIdentityKey: (account: any, keypair: any) => void;
    storeOmemoDeviceList: (chatId: any, deviceIds: any) => void;
    getOmemoDeviceList: (chatId: any, callback: any) => void;
    storeOmemoPreKey: (account: any, keyId: any, keyPair: any) => void;
    removeOmemoPreKey: (account: any, keyId: any) => void;
    getOmemoPreKey: (account: any, keyId: any, callback: any) => void;
    getOmemoPreKeys: (account: any, callback: any) => void;
    storeStreamManagement: (account: any, sm: any) => void;
    getStreamManagement(account: any): Promise<ArrayBuffer>;
    getLogin: (login: any) => Promise<{
        clientId: any;
        token: any;
        fastCount: any;
        displayName: any;
    }>;
    getOmemoId: (account: any, callback: any) => void;
    getOmemoIdentityKey: (account: any, callback: any) => void;
    getOmemoSignedPreKey: (account: any, keyId: any, callback: any) => void;
    storeOmemoSignedPreKey: (account: any, signedKey: any) => void;
    removeAccount(account: any, completely: any): void;
    listAccounts(): Promise<any>;
    storeService(account: any, serviceId: any, name: any, node: any, caps: any): void;
    findServicesWithFeature(account: any, feature: any): Promise<any[]>;
    getOmemoContactIdentityKey: (account: any, address: any, callback: any) => void;
    storeOmemoContactIdentityKey: (account: any, address: any, identityKey: any) => void;
    getOmemoSession: (account: any, address: any, callback: any) => void;
    storeOmemoSession: (account: any, address: any, session: any) => void;
    storeOmemoMetadata: (account: any, address: any, metadata: any) => void;
    getOmemoMetadata: (account: any, address: any, callback: any) => void;
    removeOmemoSession: (account: any, address: any) => void;
    get(k: any): Promise<any>;
    set(k: any, v: any): Promise<any>;
}>;
export default _default;
import { borogove_Caps } from "./borogove.js";
