/* tslint:disable */ // Generated by Haxe TypeScript Declaration Generator :)
export var snikket;
(function (snikket) {
    let UiState;
    (function (UiState) {
        UiState[UiState["Pinned"] = 0] = "Pinned";
        UiState[UiState["Open"] = 1] = "Open";
        UiState[UiState["Closed"] = 2] = "Closed";
    })(UiState = snikket.UiState || (snikket.UiState = {}));
})(snikket || (snikket = {}));
(function (snikket) {
    let MessageType;
    (function (MessageType) {
        MessageType[MessageType["MessageChat"] = 0] = "MessageChat";
        MessageType[MessageType["MessageCall"] = 1] = "MessageCall";
        MessageType[MessageType["MessageChannel"] = 2] = "MessageChannel";
        MessageType[MessageType["MessageChannelPrivate"] = 3] = "MessageChannelPrivate";
    })(MessageType = snikket.MessageType || (snikket.MessageType = {}));
})(snikket || (snikket = {}));
(function (snikket) {
    let MessageDirection;
    (function (MessageDirection) {
        MessageDirection[MessageDirection["MessageReceived"] = 0] = "MessageReceived";
        MessageDirection[MessageDirection["MessageSent"] = 1] = "MessageSent";
    })(MessageDirection = snikket.MessageDirection || (snikket.MessageDirection = {}));
})(snikket || (snikket = {}));
(function (snikket) {
    let MessageStatus;
    (function (MessageStatus) {
        MessageStatus[MessageStatus["MessagePending"] = 0] = "MessagePending";
        MessageStatus[MessageStatus["MessageDeliveredToServer"] = 1] = "MessageDeliveredToServer";
        MessageStatus[MessageStatus["MessageDeliveredToDevice"] = 2] = "MessageDeliveredToDevice";
        MessageStatus[MessageStatus["MessageFailedToSend"] = 3] = "MessageFailedToSend";
    })(MessageStatus = snikket.MessageStatus || (snikket.MessageStatus = {}));
})(snikket || (snikket = {}));
(function (snikket) {
    let UserState;
    (function (UserState) {
        UserState[UserState["Gone"] = 0] = "Gone";
        UserState[UserState["Inactive"] = 1] = "Inactive";
        UserState[UserState["Active"] = 2] = "Active";
        UserState[UserState["Composing"] = 3] = "Composing";
        UserState[UserState["Paused"] = 4] = "Paused";
    })(UserState = snikket.UserState || (snikket.UserState = {}));
})(snikket || (snikket = {}));
