/* tslint:disable */// Generated by Haxe TypeScript Declaration Generator :)

export namespace snikket {
	export const enum UiState {
		Pinned = 0,
		Open = 1,
		Closed = 2,
	}
}

export namespace snikket {
	export const enum MessageType {
		MessageChat = 0,
		MessageCall = 1,
		MessageChannel = 2,
		MessageChannelPrivate = 3,
	}
}

export namespace snikket {
	export const enum MessageDirection {
		MessageReceived = 0,
		MessageSent = 1,
	}
}

export namespace snikket {
	export const enum MessageStatus {
		MessagePending = 0,
		MessageDeliveredToServer = 1,
		MessageDeliveredToDevice = 2,
		MessageFailedToSend = 3,
	}
}

export namespace snikket {
	export const enum UserState {
		Gone = 0,
		Inactive = 1,
		Active = 2,
		Composing = 3,
		Paused = 4,
	}
}